version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend/src:/app/src
    environment:
      - ENV=development

  frontend:
    build:
      context: ./app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend/src:/app/src
      # הטריק הזה מונע מחיקה של node_modules בגלל ה-Volume שלמעלה
      - /app/node_modules
    stdin_open: true # נדרש עבור react-scripts בתוך דוקר
    tty: true